project:
  type: website
website:
  title: "Lipidomics Study"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: doc/learning.qmd
        text: "Report"
format:
  html:
    theme: simplex
knitr:
  opts_chunk:
    echo: false
editor_options:
  markdown:
    wrap: 72
    canonical: true

page-footer:
  center:
    text: "License CC BY 4.0"
