---
title: "Lipidomics Analysis"
author:
  - name: Signe Kirk Brødbæk
    affiliations:
      - name: Steno Diabetes Center Aarhus
format: html
execute:
  echo: true
---

```{r setup}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Results

```{r}
targets::tar_read(df_stats_by_metabolite) %>%
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolite = metabolite, `Mean SD` = MeanSD) %>%
  knitr::kable(caption = "Descriptive statistics of the metabolites.")

tar_read(fig_metabolite_distribution)
```

### Figure of model estimates

```{r}
model_estimates <- tar_read(df_model_estimates)
```

```{r}
tar_read(fig_model_estimates)
```

## Building the model

```{r}
lipidomics_wide <- lipidomics %>%
  column_values_to_snake_case(metabolite) %>%
  metabolites_to_wider()
```

```{r}
recipe_specs <- lipidomics_wide %>%
  create_recipe_spec(metabolite_cholesterol)
recipe_specs
```

```{r}
model_workflow <- create_model_workflow(
  logistic_reg() %>%
    set_engine("glm"),
  lipidomics_wide %>%
    create_recipe_spec(metabolite_cholesterol)
) %>%
  fit(lipidomics_wide) %>%
  tidy_model_output()
```

## Running multiple models

```{r}
model_estimates <- calculate_estimates(lipidomics)
```

## Old stuff

```{r basic-stats}
# lipidomics %>%
#   group_by(metabolite) %>%
#   summarise(across(value, list(mean = mean, sd = sd))) %>%
#   mutate(across(where(is.numeric), ~ round(.x, digits = 1)))
```

```{r basic-stats-function}
#' Calculate descriptive stats (mean and standard deviation) of each metabolite
#'
#' @param data Lipidomics dataset (loaded from csv)
#'
#' @return A data.frame/tibble
# descriptive_stats -> function(data) {
#   data %>%
#     dplyr::group_by(metabolite) %>%
#     dplyr::summarise(dplyr::across(value, list(mean = mean, sd = sd))) %>%
#     dplyr::mutate(dplyr::across(tidyselect::where(is.numeric), ~ round(.x, digits = 1)))
# }
```

```{r figure}
# metabolite_distribution_plot <- ggplot(lipidomics, aes(x = value)) +
#   geom_histogram() +
#   facet_wrap(vars(metabolite), scales = "free")
#
# metabolite_distribution_plot
```

```{r figure-function}
#' Figure showing distributions of metabolites
#'
#' @param data Lipidomics data (long format)
#'
#' @return A plot object

# plot_distributions <- function(data) {
#   ggplot2::ggplot(data, aes(x = value)) +
#     ggplot2::geom_histogram() +
#     ggplot2::facet_wrap(vars(metabolite), scales = "free")
# }
```
